language: node_js

before_install:
    - npm install contextify


node_js:
  - '0.10'

notifications:
  email: false

before_script: 
  - firefox --version
  - echo $BRANCH
#caching: true
after_script: echo $BRANCH
